insert into Books (idBooks, author, title, price, availability) values (1, 'Corny', 'Mina Tannenbaum', 622792, '8:31 PM');
insert into Books (idBooks, author, title, price, availability) values (2, 'Gunther', 'All Mine to Give', 907716, '6:37 AM');
insert into Books (idBooks, author, title, price, availability) values (3, 'Say', 'Summer Wars (Samâ wôzu)', 53426, '6:33 PM');
insert into Books (idBooks, author, title, price, availability) values (4, 'Anastasie', 'Pleasure of Being Robbed, The', 543745, '7:41 PM');
insert into Books (idBooks, author, title, price, availability) values (5, 'Maurine', 'Windstruck (Nae yeojachingureul sogae habnida)', 892485, '3:02 AM');
insert into Books (idBooks, author, title, price, availability) values (6, 'Nye', 'City Lights', 932022, '10:01 AM');
insert into Books (idBooks, author, title, price, availability) values (7, 'Tab', 'Haunting of Molly Hartley, The', 29511, '10:40 PM');
insert into Books (idBooks, author, title, price, availability) values (8, 'Reggy', 'Rabbit Test', 411525, '9:53 PM');
insert into Books (idBooks, author, title, price, availability) values (9, 'Bernie', '21 and Over', 573082, '1:28 AM');
insert into Books (idBooks, author, title, price, availability) values (10, 'Dorise', 'Puerta de Hierro, el exilio de Perón', 492395, '6:47 AM');
insert into Books (idBooks, author, title, price, availability) values (11, 'Cristiano', 'We Don''t Live Here Anymore', 376630, '2:21 PM');
insert into Books (idBooks, author, title, price, availability) values (12, 'Boyd', 'Holy Flame of the Martial World (Wu lin sheng huo jin)', 518781, '2:41 PM');
insert into Books (idBooks, author, title, price, availability) values (13, 'Olia', 'Why Man Creates', 356049, '8:06 PM');
insert into Books (idBooks, author, title, price, availability) values (14, 'Pinchas', 'Hunter, The', 988345, '12:53 AM');
insert into Books (idBooks, author, title, price, availability) values (15, 'Emmie', 'Subject Was Roses, The', 974090, '1:36 PM');
insert into Books (idBooks, author, title, price, availability) values (16, 'Audry', 'Hostel', 156788, '10:47 PM');
insert into Books (idBooks, author, title, price, availability) values (17, 'Sisely', 'Somebody to Love', 743470, '2:41 PM');
insert into Books (idBooks, author, title, price, availability) values (18, 'Jeannie', 'Knucklehead', 91408, '11:48 AM');
insert into Books (idBooks, author, title, price, availability) values (19, 'Barbabra', 'Tarzan Escapes', 699295, '2:22 AM');
insert into Books (idBooks, author, title, price, availability) values (20, 'Ailee', 'Two Much', 436199, '11:26 AM');
insert into Books (idBooks, author, title, price, availability) values (21, 'Moise', 'DOA: Dead or Alive', 486873, '1:19 PM');
insert into Books (idBooks, author, title, price, availability) values (22, 'Rudolfo', 'Land of the Dead', 27352, '9:17 AM');
insert into Books (idBooks, author, title, price, availability) values (23, 'Eadith', 'Wizard of Oz, The', 605553, '1:05 PM');
insert into Books (idBooks, author, title, price, availability) values (24, 'Minerva', 'Crime of Monsieur Lange, The (Le crime de Monsieur Lange)', 493396, '1:39 AM');
insert into Books (idBooks, author, title, price, availability) values (25, 'Doll', 'Catch .44', 583898, '1:02 AM');
insert into Books (idBooks, author, title, price, availability) values (26, 'Guntar', 'Alvin and the Chipmunks: Chipwrecked', 983978, '4:09 PM');
insert into Books (idBooks, author, title, price, availability) values (27, 'Dorena', 'Little Mermaid 2: Return to the Sea, The', 999419, '3:19 PM');
insert into Books (idBooks, author, title, price, availability) values (28, 'Brigham', 'Safe Passage', 564926, '12:21 AM');
insert into Books (idBooks, author, title, price, availability) values (29, 'Randie', 'Rains of Ranchipur, The', 239168, '5:43 PM');
insert into Books (idBooks, author, title, price, availability) values (30, 'Odo', 'Mr. Peabody & Sherman', 146984, '7:19 AM');
insert into Books (idBooks, author, title, price, availability) values (31, 'Reyna', 'Hot Spot, The', 989489, '9:14 AM');
insert into Books (idBooks, author, title, price, availability) values (32, 'Vachel', 'Friends of God: A Road Trip with Alexandra Pelosi', 451108, '2:33 AM');
insert into Books (idBooks, author, title, price, availability) values (33, 'Thebault', 'Guns, Girls and Gambling', 773574, '4:55 AM');
insert into Books (idBooks, author, title, price, availability) values (34, 'Vinni', 'NeverEnding Story II: The Next Chapter, The', 12284, '9:15 PM');
insert into Books (idBooks, author, title, price, availability) values (35, 'Leena', 'Calendar Girl', 287075, '8:11 AM');
insert into Books (idBooks, author, title, price, availability) values (36, 'Gwenette', 'Daens', 522907, '3:21 AM');
insert into Books (idBooks, author, title, price, availability) values (37, 'Guillema', 'V2: Dead Angel (Vares 2 - Jäätynyt Enkeli)', 703204, '6:04 PM');
insert into Books (idBooks, author, title, price, availability) values (38, 'Kirstin', 'Leading Man, The', 905102, '1:05 AM');
insert into Books (idBooks, author, title, price, availability) values (39, 'Shana', 'Female', 857061, '8:22 AM');
insert into Books (idBooks, author, title, price, availability) values (40, 'Berte', 'Good-bye, My Lady', 214656, '2:28 AM');
insert into Books (idBooks, author, title, price, availability) values (41, 'Tildy', 'Leslie, My Name is Evil (Manson, My Name is Evil)', 30039, '8:04 AM');
insert into Books (idBooks, author, title, price, availability) values (42, 'Dina', 'My Wrongs 8245-8249 and 117', 224612, '11:36 AM');
insert into Books (idBooks, author, title, price, availability) values (43, 'Sherri', 'High Noon', 812250, '12:20 AM');
insert into Books (idBooks, author, title, price, availability) values (44, 'Fabian', 'Sound of Fury, The', 525010, '3:38 AM');
insert into Books (idBooks, author, title, price, availability) values (45, 'Gigi', 'Other Boleyn Girl, The', 279708, '6:47 AM');
insert into Books (idBooks, author, title, price, availability) values (46, 'Welbie', 'Case départ', 60542, '10:13 AM');
insert into Books (idBooks, author, title, price, availability) values (47, 'Ki', 'Nada Gang, The (Nada)', 722682, '3:44 PM');
insert into Books (idBooks, author, title, price, availability) values (48, 'Perry', 'Bewitched (Alter Ego)', 369948, '1:15 PM');
insert into Books (idBooks, author, title, price, availability) values (49, 'Lynnelle', 'Poseidon', 746440, '5:43 PM');
insert into Books (idBooks, author, title, price, availability) values (50, 'Nicolais', 'City Slickers', 497982, '11:32 PM');
insert into Books (idBooks, author, title, price, availability) values (51, 'Lorenzo', 'Fist of the North Star', 644312, '1:12 AM');
insert into Books (idBooks, author, title, price, availability) values (52, 'Constancy', 'Some Days Are Better Than Others', 716264, '6:36 PM');
insert into Books (idBooks, author, title, price, availability) values (53, 'Vere', 'Way You Wanted Me, The (Sellaisena kuin sinä minut halusit)', 446525, '12:52 AM');
insert into Books (idBooks, author, title, price, availability) values (54, 'Gloriane', 'Nazarin (Nazarín)', 907854, '2:55 PM');
insert into Books (idBooks, author, title, price, availability) values (55, 'Farlee', 'Milwaukee, Minnesota', 370315, '6:09 AM');
insert into Books (idBooks, author, title, price, availability) values (56, 'Nickolaus', 'Von Richthofen and Brown', 920733, '6:02 AM');
insert into Books (idBooks, author, title, price, availability) values (57, 'Jan', 'Space Milkshake', 668924, '9:45 PM');
insert into Books (idBooks, author, title, price, availability) values (58, 'Anabal', 'Pontiac Moon', 598816, '7:49 AM');
insert into Books (idBooks, author, title, price, availability) values (59, 'Tremaine', 'Less Than Zero', 728483, '6:54 PM');
insert into Books (idBooks, author, title, price, availability) values (60, 'Augustine', 'Last Year at Marienbad (L''Année dernière à Marienbad)', 292457, '12:43 PM');
insert into Books (idBooks, author, title, price, availability) values (61, 'Gram', 'Katy Perry: Part of Me', 520173, '7:56 AM');
insert into Books (idBooks, author, title, price, availability) values (62, 'Petronille', 'Hallelujah!', 499840, '8:10 PM');
insert into Books (idBooks, author, title, price, availability) values (63, 'Carlin', 'Thorn Birds, The', 118882, '11:34 AM');
insert into Books (idBooks, author, title, price, availability) values (64, 'Dulci', 'Hori Smoku Sailor Jerry: The Life of Norman K. Collins ', 12732, '11:27 AM');
insert into Books (idBooks, author, title, price, availability) values (65, 'Rusty', 'Making ''The New World''', 847218, '1:48 PM');
insert into Books (idBooks, author, title, price, availability) values (66, 'Brade', 'K-9', 455139, '2:08 AM');
insert into Books (idBooks, author, title, price, availability) values (67, 'Bryn', 'Scarecrows', 3437, '7:35 PM');
insert into Books (idBooks, author, title, price, availability) values (68, 'Reeba', 'Making ''The New World''', 247499, '9:16 PM');
insert into Books (idBooks, author, title, price, availability) values (69, 'Ailene', 'Bullfighter, The (Matador)', 388432, '3:26 PM');
insert into Books (idBooks, author, title, price, availability) values (70, 'Town', 'Who Is Killing the Great Chefs of Europe?', 105465, '2:13 PM');
insert into Books (idBooks, author, title, price, availability) values (71, 'Amii', 'Greaser''s Palace', 844645, '10:45 AM');
insert into Books (idBooks, author, title, price, availability) values (72, 'Cleon', 'Ref, The', 655649, '1:39 AM');
insert into Books (idBooks, author, title, price, availability) values (73, 'Bryna', 'Planet of the Apes', 834420, '3:41 AM');
insert into Books (idBooks, author, title, price, availability) values (74, 'Janice', 'Odessa File, The', 564393, '11:36 AM');
insert into Books (idBooks, author, title, price, availability) values (75, 'Shay', 'Wake Up, Ron Burgundy', 882423, '2:46 PM');
insert into Books (idBooks, author, title, price, availability) values (76, 'Allegra', 'Black Box, The (La boîte noire)', 240800, '1:57 PM');
insert into Books (idBooks, author, title, price, availability) values (77, 'Gwenette', 'Handmaid''s Tale, The', 433005, '2:38 PM');
insert into Books (idBooks, author, title, price, availability) values (78, 'Caz', 'Bugs Bunny / Road Runner Movie, The (a.k.a. The Great American Chase)', 692922, '9:18 AM');
insert into Books (idBooks, author, title, price, availability) values (79, 'Tiena', 'Blood Money', 727403, '1:27 PM');
insert into Books (idBooks, author, title, price, availability) values (80, 'Horten', 'Waiting to Exhale', 505431, '8:55 PM');
insert into Books (idBooks, author, title, price, availability) values (81, 'Friedrick', 'Elaine Stritch: Shoot Me', 95143, '12:25 PM');
insert into Books (idBooks, author, title, price, availability) values (82, 'Manon', 'Soldier''s Sweetheart, A', 732786, '8:38 PM');
insert into Books (idBooks, author, title, price, availability) values (83, 'Bradan', 'Harvard Man', 302999, '8:12 AM');
insert into Books (idBooks, author, title, price, availability) values (84, 'Robinia', 'Dean Spanley', 839862, '7:21 AM');
insert into Books (idBooks, author, title, price, availability) values (85, 'Ernestus', 'Left Behind', 340244, '1:10 AM');
insert into Books (idBooks, author, title, price, availability) values (86, 'Gottfried', 'My Brother''s Wife (Mujer de mi hermano, La)', 136233, '10:42 AM');
insert into Books (idBooks, author, title, price, availability) values (87, 'Marv', 'Fall of the House of Usher, The (Zánik domu Usheru)', 266095, '10:23 PM');
insert into Books (idBooks, author, title, price, availability) values (88, 'Rosaleen', 'Jaws 3-D', 415812, '8:36 PM');
insert into Books (idBooks, author, title, price, availability) values (89, 'Norina', 'Fudoh: The New Generation (Gokudô sengokushi: Fudô)', 54100, '9:56 AM');
insert into Books (idBooks, author, title, price, availability) values (90, 'Marcellus', 'Exiled (Fong juk)', 954753, '9:03 AM');
insert into Books (idBooks, author, title, price, availability) values (91, 'Ofilia', 'Solino', 886356, '8:05 PM');
insert into Books (idBooks, author, title, price, availability) values (92, 'Cosetta', 'In America', 951926, '5:52 PM');
insert into Books (idBooks, author, title, price, availability) values (93, 'Chiquia', 'Lights in the Dusk (Laitakaupungin valot)', 749537, '6:23 PM');
insert into Books (idBooks, author, title, price, availability) values (94, 'Carline', 'I Spit on Your Grave (Day of the Woman)', 613425, '5:16 PM');
insert into Books (idBooks, author, title, price, availability) values (95, 'Hans', 'Her', 737506, '5:32 AM');
insert into Books (idBooks, author, title, price, availability) values (96, 'Regan', 'Silent Night, Deadly Night III: Better Watch Out!', 76315, '11:16 AM');
insert into Books (idBooks, author, title, price, availability) values (97, 'Parke', 'How to Make Love to a Woman', 141327, '6:44 PM');
insert into Books (idBooks, author, title, price, availability) values (98, 'Jake', 'Out of Africa', 309401, '12:11 AM');
insert into Books (idBooks, author, title, price, availability) values (99, 'Alli', 'Thing: Terror Takes Shape, The', 98845, '6:32 PM');
insert into Books (idBooks, author, title, price, availability) values (100, 'Polly', 'Tru Confessions', 142669, '7:39 PM');
