insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (1, '11/4/2020', 'Isaiah Aldam', '2 Lyons Terrace', 'M', 'Product Management');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (2, '7/8/2021', 'Horatius Sturley', '66259 Clarendon Park', 'M', 'Support');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (3, '7/10/2021', 'Matthaeus Cawker', '1013 Barnett Trail', 'M', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (4, '11/10/2020', 'Salomon Balwin', '4 Chinook Terrace', 'M', 'Human Resources');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (5, '1/3/2021', 'Delainey Alpes', '8 Monterey Alley', 'M', 'Marketing');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (6, '12/29/2020', 'Holly Collimore', '06090 Express Crossing', 'F', 'Training');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (7, '12/27/2020', 'Tedman Blazynski', '5 Schurz Place', 'M', 'Services');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (8, '9/14/2020', 'Corbin McKue', '9 Gale Avenue', 'M', 'Human Resources');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (9, '3/17/2021', 'Cherey Grigsby', '81187 Scoville Avenue', 'F', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (10, '2/17/2021', 'Brandy Broomhall', '0188 South Hill', 'M', 'Services');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (11, '9/26/2020', 'Tomasina Slainey', '41 Heath Street', 'F', 'Legal');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (12, '1/9/2021', 'Ivy Gavin', '49623 Old Gate Hill', 'F', 'Accounting');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (13, '4/24/2021', 'Jeremy Pollitt', '57 Autumn Leaf Circle', 'M', 'Human Resources');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (14, '1/19/2021', 'Amalie Viles', '315 Iowa Plaza', 'F', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (15, '7/10/2021', 'Inglebert Brimilcombe', '163 Harbort Plaza', 'M', 'Marketing');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (16, '5/22/2021', 'Sophia Olman', '75 Maryland Plaza', 'F', 'Services');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (17, '7/11/2021', 'Ulick Clementucci', '8268 Butternut Park', 'M', 'Legal');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (18, '10/19/2020', 'Dodi Thornthwaite', '6830 Arkansas Hill', 'F', 'Business Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (19, '7/1/2021', 'Bailey Jowling', '4 Sunfield Parkway', 'M', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (20, '7/25/2021', 'Estrellita Crocetti', '72940 Westridge Circle', 'F', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (21, '12/5/2020', 'Padraic Gerrelt', '62 Garrison Parkway', 'M', 'Business Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (22, '7/14/2021', 'Muriel Meggison', '743 Melvin Circle', 'F', 'Business Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (23, '6/3/2021', 'Clo Gillian', '639 Schmedeman Drive', 'F', 'Accounting');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (24, '8/12/2020', 'Ingemar Maulden', '51725 Melvin Avenue', 'M', 'Training');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (25, '4/21/2021', 'Skyler Kuhnwald', '63660 Continental Court', 'M', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (26, '3/20/2021', 'Kimbra Jobbing', '40018 Kipling Lane', 'F', 'Engineering');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (27, '1/31/2021', 'Dosi Yukhnini', '65370 Rockefeller Lane', 'F', 'Engineering');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (28, '2/27/2021', 'Jojo Skeggs', '1633 Warbler Way', 'F', 'Legal');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (29, '8/11/2020', 'Anneliese Brookes', '37 Elgar Avenue', 'F', 'Engineering');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (30, '6/23/2021', 'Menard Werlock', '6502 Darwin Junction', 'M', 'Training');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (31, '3/28/2021', 'Alasteir Wigginton', '8235 American Ash Court', 'M', 'Accounting');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (32, '5/13/2021', 'Camella Dunham', '91988 Thierer Plaza', 'F', 'Product Management');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (33, '4/20/2021', 'Emmey Guyonneau', '22 Holy Cross Junction', 'F', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (34, '6/24/2021', 'Roddy Bigham', '88413 East Parkway', 'M', 'Engineering');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (35, '7/24/2021', 'Brook Saipy', '836 3rd Terrace', 'M', 'Human Resources');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (36, '7/16/2021', 'Corty Waterdrinker', '37 Superior Street', 'M', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (37, '4/26/2021', 'Clement De Brett', '93 Northport Drive', 'M', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (38, '7/10/2021', 'Grenville Priel', '76 Lunder Place', 'M', 'Human Resources');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (39, '12/30/2020', 'Drake Rosevear', '46 Bonner Drive', 'M', 'Services');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (40, '1/26/2021', 'Jacki Mougenel', '34 Waywood Avenue', 'F', 'Training');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (41, '6/24/2021', 'Erik Ianilli', '7825 Sundown Way', 'M', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (42, '2/25/2021', 'Alfi Rockwell', '6441 Merry Lane', 'F', 'Product Management');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (43, '4/14/2021', 'Bearnard Hawker', '2172 Sunfield Alley', 'M', 'Legal');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (44, '4/17/2021', 'Kincaid Dartnall', '1 Vidon Circle', 'M', 'Legal');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (45, '2/18/2021', 'Gael Undrill', '0 Elka Place', 'M', 'Marketing');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (46, '7/15/2021', 'Brew Torn', '983 Blue Bill Park Street', 'M', 'Accounting');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (47, '12/3/2020', 'Verena Bransgrove', '2597 Walton Street', 'F', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (48, '1/15/2021', 'Blaine Neath', '38 Nancy Crossing', 'M', 'Legal');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (49, '10/31/2020', 'Bo L''Archer', '7823 Prairieview Circle', 'M', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (50, '11/14/2020', 'Carl Marriott', '24 Iowa Hill', 'M', 'Support');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (51, '12/2/2020', 'Franklin Gunderson', '2 Northland Hill', 'M', 'Services');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (52, '3/4/2021', 'Dael Savill', '1 Warbler Plaza', 'F', 'Training');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (53, '8/12/2020', 'Porter Bolus', '6 Brown Terrace', 'M', 'Business Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (54, '3/31/2021', 'Marthena Kimmins', '6 Hanover Junction', 'F', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (55, '10/18/2020', 'Faulkner Wathen', '76 Pankratz Court', 'M', 'Business Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (56, '9/27/2020', 'Vallie Lansbury', '57 Kenwood Way', 'F', 'Services');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (57, '2/22/2021', 'Margy Billings', '3 Esch Parkway', 'F', 'Accounting');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (58, '4/14/2021', 'Ethelin Ulrik', '1275 Kinsman Terrace', 'F', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (59, '8/8/2020', 'Darbie Ranson', '68 Mallard Avenue', 'F', 'Training');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (60, '9/28/2020', 'Berget Skeeles', '44365 Erie Park', 'F', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (61, '10/23/2020', 'Thornton Syne', '74391 Muir Point', 'M', 'Engineering');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (62, '11/6/2020', 'Arvy Josupeit', '5 Boyd Drive', 'M', 'Support');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (63, '11/5/2020', 'Carmella Herreran', '2 Maple Wood Alley', 'F', 'Support');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (64, '1/18/2021', 'Blythe Leate', '4 Havey Circle', 'F', 'Product Management');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (65, '2/17/2021', 'Ade Woodeson', '0 Glacier Hill Crossing', 'M', 'Services');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (66, '7/24/2021', 'Olvan Martland', '1 Scoville Parkway', 'M', 'Marketing');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (67, '5/13/2021', 'Phedra Cleife', '14007 Granby Circle', 'F', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (68, '9/7/2020', 'Jesse Thalmann', '8670 Merrick Road', 'M', 'Training');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (69, '10/30/2020', 'Vidovik Vannet', '38 Emmet Place', 'M', 'Legal');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (70, '6/29/2021', 'Editha Thoresby', '70852 Spohn Place', 'F', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (71, '9/4/2020', 'Peg O''Dulchonta', '4609 Moose Point', 'F', 'Legal');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (72, '7/3/2021', 'Randy Chastenet', '1 Rigney Drive', 'M', 'Legal');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (73, '4/3/2021', 'Branden Ianniello', '465 Southridge Street', 'M', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (74, '1/22/2021', 'Lauritz Boise', '917 Mockingbird Trail', 'M', 'Marketing');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (75, '3/16/2021', 'Trent Kilgannon', '01898 Artisan Trail', 'M', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (76, '2/23/2021', 'Emiline Giraudoux', '9971 Loomis Hill', 'F', 'Services');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (77, '4/13/2021', 'Blancha Croix', '60 Iowa Place', 'F', 'Legal');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (78, '10/29/2020', 'Lauren Troman', '32091 Sycamore Drive', 'F', 'Human Resources');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (79, '9/9/2020', 'Oliviero Caulliere', '50 Ridgeview Circle', 'M', 'Marketing');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (80, '8/22/2020', 'Milo Adnett', '28734 Continental Court', 'M', 'Business Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (81, '4/14/2021', 'Nickolas Pilmore', '1 Elgar Place', 'M', 'Training');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (82, '10/20/2020', 'Cecil Loynes', '5500 Paget Parkway', 'M', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (83, '8/12/2020', 'Bradley Jurasek', '404 Westend Lane', 'M', 'Human Resources');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (84, '7/16/2021', 'Tami Fidelli', '9 Loomis Avenue', 'F', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (85, '6/17/2021', 'Meredithe Suddock', '9212 Autumn Leaf Terrace', 'F', 'Product Management');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (86, '7/6/2021', 'Beatrix Dukelow', '018 Hallows Court', 'F', 'Engineering');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (87, '1/7/2021', 'Guthry Aitcheson', '03725 Milwaukee Way', 'M', 'Support');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (88, '9/6/2020', 'Iosep Ellissen', '8324 Veith Avenue', 'M', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (89, '7/3/2021', 'Aretha Levene', '88 4th Parkway', 'F', 'Marketing');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (90, '10/26/2020', 'Carmelina Ryce', '3 Superior Street', 'F', 'Support');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (91, '8/22/2020', 'Jermayne Glandfield', '17 Truax Hill', 'M', 'Accounting');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (92, '1/11/2021', 'Ertha Merdew', '0753 Rutledge Circle', 'F', 'Training');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (93, '12/11/2020', 'Glynda Whitelaw', '579 Elgar Trail', 'F', 'Product Management');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (94, '4/16/2021', 'Seymour Caile', '34 Farragut Junction', 'M', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (95, '8/1/2021', 'Hildagarde Zupo', '90 Gale Park', 'F', 'Support');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (96, '5/15/2021', 'Fernanda MacNelly', '8 Pennsylvania Alley', 'F', 'Research and Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (97, '1/29/2021', 'Bryan Witts', '94716 Iowa Avenue', 'M', 'Business Development');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (98, '11/19/2020', 'Gradey Udell', '84 Vernon Junction', 'M', 'Accounting');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (99, '1/11/2021', 'Valaria Tommen', '3 American Ash Center', 'F', 'Sales');
insert into Members (idMember, expiryDate, attriName, address, membType, membInfo) values (100, '10/23/2020', 'Dari Flather', '28 Lerdahl Road', 'F', 'Product Management');
