insert into Publishers (idPublisher, address, name) values (1, '5993 Ruskin Avenue', 'Oozz');
insert into Publishers (idPublisher, address, name) values (2, '37 Hoepker Crossing', 'Demimbu');
insert into Publishers (idPublisher, address, name) values (3, '8 Golf View Point', 'Tagfeed');
insert into Publishers (idPublisher, address, name) values (4, '419 Service Terrace', 'Thoughtbridge');
insert into Publishers (idPublisher, address, name) values (5, '2734 Talmadge Avenue', 'Zoombeat');
insert into Publishers (idPublisher, address, name) values (6, '5737 Farmco Hill', 'Mybuzz');
insert into Publishers (idPublisher, address, name) values (7, '3 Sloan Pass', 'Leenti');
insert into Publishers (idPublisher, address, name) values (8, '417 Ohio Street', 'Rhyzio');
insert into Publishers (idPublisher, address, name) values (9, '1301 6th Lane', 'Skinte');
insert into Publishers (idPublisher, address, name) values (10, '5436 Heffernan Lane', 'Dabjam');
insert into Publishers (idPublisher, address, name) values (11, '23793 Morrow Point', 'Thoughtstorm');
insert into Publishers (idPublisher, address, name) values (12, '91357 Chinook Hill', 'Kimia');
insert into Publishers (idPublisher, address, name) values (13, '18708 Kingsford Park', 'Gabcube');
insert into Publishers (idPublisher, address, name) values (14, '6 Nevada Hill', 'Photobug');
insert into Publishers (idPublisher, address, name) values (15, '11975 Eagle Crest Way', 'Camido');
insert into Publishers (idPublisher, address, name) values (16, '04 Merry Pass', 'Thoughtsphere');
insert into Publishers (idPublisher, address, name) values (17, '93 Paget Way', 'Vipe');
insert into Publishers (idPublisher, address, name) values (18, '88475 Ronald Regan Crossing', 'Quimba');
insert into Publishers (idPublisher, address, name) values (19, '487 Hermina Pass', 'Centizu');
insert into Publishers (idPublisher, address, name) values (20, '0 Lotheville Terrace', 'Wikido');
insert into Publishers (idPublisher, address, name) values (21, '98 Farwell Alley', 'Edgeclub');
insert into Publishers (idPublisher, address, name) values (22, '9586 Division Avenue', 'Tagfeed');
insert into Publishers (idPublisher, address, name) values (23, '51 Charing Cross Drive', 'Linklinks');
insert into Publishers (idPublisher, address, name) values (24, '2 Paget Point', 'Agivu');
insert into Publishers (idPublisher, address, name) values (25, '4488 Tomscot Court', 'Zooxo');
insert into Publishers (idPublisher, address, name) values (26, '39273 New Castle Terrace', 'Flashset');
insert into Publishers (idPublisher, address, name) values (27, '96 Glacier Hill Parkway', 'Wordtune');
insert into Publishers (idPublisher, address, name) values (28, '28 Dovetail Terrace', 'Talane');
insert into Publishers (idPublisher, address, name) values (29, '23066 Buena Vista Circle', 'Bluejam');
insert into Publishers (idPublisher, address, name) values (30, '56 Hayes Trail', 'Feedfire');
insert into Publishers (idPublisher, address, name) values (31, '74 Stephen Hill', 'Mymm');
insert into Publishers (idPublisher, address, name) values (32, '08990 Goodland Junction', 'Topicblab');
insert into Publishers (idPublisher, address, name) values (33, '2 Washington Point', 'Skipstorm');
insert into Publishers (idPublisher, address, name) values (34, '11 Fairfield Center', 'Eire');
insert into Publishers (idPublisher, address, name) values (35, '2 Maywood Avenue', 'Leenti');
insert into Publishers (idPublisher, address, name) values (36, '83 Loftsgordon Center', 'Devpulse');
insert into Publishers (idPublisher, address, name) values (37, '761 Golf Course Road', 'Mybuzz');
insert into Publishers (idPublisher, address, name) values (38, '741 Novick Hill', 'Avamba');
insert into Publishers (idPublisher, address, name) values (39, '3406 Sunfield Crossing', 'Voonte');
insert into Publishers (idPublisher, address, name) values (40, '489 Scofield Alley', 'Skalith');
insert into Publishers (idPublisher, address, name) values (41, '705 Morningstar Street', 'Izio');
insert into Publishers (idPublisher, address, name) values (42, '209 Ridgeview Hill', 'Quaxo');
insert into Publishers (idPublisher, address, name) values (43, '7324 Holy Cross Center', 'Tagtune');
insert into Publishers (idPublisher, address, name) values (44, '64 Moose Circle', 'Bluejam');
insert into Publishers (idPublisher, address, name) values (45, '5 Anniversary Point', 'Digitube');
insert into Publishers (idPublisher, address, name) values (46, '9 Reindahl Center', 'Jayo');
insert into Publishers (idPublisher, address, name) values (47, '3 Sycamore Point', 'Zoomzone');
insert into Publishers (idPublisher, address, name) values (48, '88 Orin Pass', 'Jazzy');
insert into Publishers (idPublisher, address, name) values (49, '64354 Lerdahl Court', 'Agimba');
insert into Publishers (idPublisher, address, name) values (50, '0 Cordelia Pass', 'Eabox');
insert into Publishers (idPublisher, address, name) values (51, '00695 Bluestem Court', 'Vidoo');
insert into Publishers (idPublisher, address, name) values (52, '5 Drewry Point', 'Browsebug');
insert into Publishers (idPublisher, address, name) values (53, '4 Hooker Hill', 'LiveZ');
insert into Publishers (idPublisher, address, name) values (54, '6389 Sachs Place', 'Topiclounge');
insert into Publishers (idPublisher, address, name) values (55, '05869 Evergreen Hill', 'Gigabox');
insert into Publishers (idPublisher, address, name) values (56, '27 Badeau Trail', 'Yambee');
insert into Publishers (idPublisher, address, name) values (57, '1951 Helena Alley', 'Meezzy');
insert into Publishers (idPublisher, address, name) values (58, '80 Fallview Junction', 'Kazio');
insert into Publishers (idPublisher, address, name) values (59, '72919 Pond Trail', 'Jetwire');
insert into Publishers (idPublisher, address, name) values (60, '31789 New Castle Court', 'Yodoo');
insert into Publishers (idPublisher, address, name) values (61, '3100 Springs Avenue', 'Layo');
insert into Publishers (idPublisher, address, name) values (62, '1704 West Court', 'Voonix');
insert into Publishers (idPublisher, address, name) values (63, '47 Harbort Way', 'Skippad');
insert into Publishers (idPublisher, address, name) values (64, '316 Transport Hill', 'Browsebug');
insert into Publishers (idPublisher, address, name) values (65, '99 Tennyson Road', 'Agivu');
insert into Publishers (idPublisher, address, name) values (66, '2 Dahle Point', 'Browsebug');
insert into Publishers (idPublisher, address, name) values (67, '08 Aberg Hill', 'Centidel');
insert into Publishers (idPublisher, address, name) values (68, '48 Lukken Trail', 'Meeveo');
insert into Publishers (idPublisher, address, name) values (69, '7123 Red Cloud Court', 'Dynabox');
insert into Publishers (idPublisher, address, name) values (70, '18 Memorial Pass', 'Zooxo');
insert into Publishers (idPublisher, address, name) values (71, '674 Myrtle Lane', 'Babbleset');
insert into Publishers (idPublisher, address, name) values (72, '9761 Service Road', 'Skyndu');
insert into Publishers (idPublisher, address, name) values (73, '354 Bellgrove Junction', 'Yakijo');
insert into Publishers (idPublisher, address, name) values (74, '180 Loftsgordon Street', 'Edgeblab');
insert into Publishers (idPublisher, address, name) values (75, '5524 Hansons Avenue', 'Rhycero');
insert into Publishers (idPublisher, address, name) values (76, '13 Morning Park', 'Demimbu');
insert into Publishers (idPublisher, address, name) values (77, '0367 Montana Place', 'Quire');
insert into Publishers (idPublisher, address, name) values (78, '585 Porter Alley', 'Quatz');
insert into Publishers (idPublisher, address, name) values (79, '81 Stang Lane', 'Jabbertype');
insert into Publishers (idPublisher, address, name) values (80, '05388 Shoshone Avenue', 'Mudo');
insert into Publishers (idPublisher, address, name) values (81, '4 Red Cloud Avenue', 'Yozio');
insert into Publishers (idPublisher, address, name) values (82, '46736 Bartillon Plaza', 'Eadel');
insert into Publishers (idPublisher, address, name) values (83, '8 Norway Maple Lane', 'Flipstorm');
insert into Publishers (idPublisher, address, name) values (84, '28049 Ramsey Street', 'Avaveo');
insert into Publishers (idPublisher, address, name) values (85, '18 Mendota Junction', 'Livefish');
insert into Publishers (idPublisher, address, name) values (86, '714 Dexter Junction', 'Zoozzy');
insert into Publishers (idPublisher, address, name) values (87, '1 Farwell Crossing', 'Twinder');
insert into Publishers (idPublisher, address, name) values (88, '657 Beilfuss Plaza', 'Feedbug');
insert into Publishers (idPublisher, address, name) values (89, '95236 Haas Lane', 'JumpXS');
insert into Publishers (idPublisher, address, name) values (90, '0 Debs Trail', 'Feedfire');
insert into Publishers (idPublisher, address, name) values (91, '88437 1st Park', 'Demizz');
insert into Publishers (idPublisher, address, name) values (92, '972 Delaware Parkway', 'Talane');
insert into Publishers (idPublisher, address, name) values (93, '720 Mitchell Circle', 'Jatri');
insert into Publishers (idPublisher, address, name) values (94, '87 Warbler Street', 'Livefish');
insert into Publishers (idPublisher, address, name) values (95, '0854 Moulton Drive', 'Flashdog');
insert into Publishers (idPublisher, address, name) values (96, '89622 Oneill Terrace', 'Quamba');
insert into Publishers (idPublisher, address, name) values (97, '72916 Dorton Parkway', 'Ntag');
insert into Publishers (idPublisher, address, name) values (98, '32 Express Road', 'Bubblemix');
insert into Publishers (idPublisher, address, name) values (99, '36 Ilene Hill', 'Trilith');
insert into Publishers (idPublisher, address, name) values (100, '98 Clyde Gallagher Pass', 'Mydeo');
